#!/bin/bash

# This script uses the Plex API to query for any streams in progress.
# It requires that the Plex server be setup to allow the local ip access without authentication.

# Set this equal to the ip of your plex server (it needs to be the actual ip, not localhost:32400 or 127.0.0.1:32400)
PLEX_URL="<your_ip>:32400"

if [[ ! $(curl --silent http://$PLEX_URL/status/sessions | grep -c "MediaContainer size=\"0\"") -eq 0 ]]
then
  exit 0
fi

exit 1
