name: Build Project

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Tests
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build CLI
        run: go build -o cli -v cmd/cli/main.go

      - name: Build Daemon
        run: go build -o daemon -v cmd/daemon/main.go
